### ISSUE TITLE
Separated Hat and Shirt for Color Code editor

### ISSUE THREAD

**Issue by GlitchyPSIX** [projectcomet64/M64MM#1]
Jme H has commented in several videos from M64MM to ask about a feature to separate both hat and overalls, unlike the current CCS behavior, which could potentially allow for bigger CC customization in the near future for vanilla ROMs (And some derivatives, maybe? like Cjes' Luigi)

The gameshark is located [here.](https://dudaw.webs.com/gameshark/sm64.txt)

There may be more to this.

**Comment by changthesomething** [comment]
The hyperlink you provided refers to the GameShark code list, not the video demonstrating the GameShark cheat code. You might want to fix that.

**Comment by GlitchyPSIX** [comment]
There are some things that Mario's default model constricts. This will be looked at more deeply later.

**Comment by GlitchyPSIX** [comment]
hahahaha [cometspark](https://github.com/projectcomet64/SPARK)
