### ISSUE TITLE
Issues with the hud modifier

### ISSUE THREAD

**Issue by xen0va** [projectcomet64/M64MM#12]
The hud modifier doesn't present the intended behavior: Depending on circumstances, the modifier doesn't work at all, in some instances it hides only part of the hud elements, and in others it fully disables them, but you cannot re-enable them.
Results seem to vary depending on emulator and ROM.

Update Nº1
Issue seems to be emulator related.
Works perfectly on Project64 1.7, has issues in some ROMs on 2.3 and has the most issues on 1.6/1.6.1.

1. Project64 1.6/1.6.1

- **Vanilla (unmodified) ROMs on PJ64 1.6/1.6.1**
Castle Grounds & Inside Peach's Castle = Fully disables hud (Only goes into effect after entering a stage) (Cannot be re-enabled) 
BoB/WF = Modifier doesn't work at all

- **Extended ROM (ROM Extender tool) on PJ64 1.6/1.6.1**
Castle Grounds, Inside Peach's Castle, BoB and WF: Fully disables hud (Cannot be re-enabled)

- **ROM Manager modified ROM**
Castle Grounds, Inside Peach's Castle, BoB and WF: Fully disables hud (Cannot be re-enabled)

**Note that once you attempt to change the hud on 1.6/1.6.1, it seems like it cannot be modified again (regardless of ROM). Example: If you only disable part of the hud elements, and then try to disable the rest, it will not work. I believe there might be something preventing M64MM from properly writing the values.**

2. Project64 1.7 

- **Works almost perfectly on all instances**
It had issues re-enabling the star counter on all 3 ROMs while on Castle Grounds/Peach's Castle.
Seems to have issues re-enabling the Power Meter on the **Extended ROM (ROM Extender tool)**.
(Requires more in-depth testing).

3. Project64 2.3

- **Mostly the same as PJ64 1.7**
(Requires more in-depth testing)

(Will add more information as I find it)

**Comment by GlitchyPSIX** [comment]
Looks like 1.6 has the most issues.
It might also have to do with which tool the ROM was extended with. This may see an improvement soon.

**Comment by GlitchyPSIX** [comment]
I'd say most issues are resolved up to where I can, thanks for reporting this
If anything arises I think it'll be for a hotfix
