### ISSUE TITLE
Spasm Feature Request

### ISSUE THREAD

**Issue by ninjaraven** [projectcomet64/M64MM#14]
It would be really cool to have an easy way to make mario spasm out (like in the old sm64 bloopers/machinimas), inside M64MM itself, without the use of savestates or rom corruption.

**Comment by GlitchyPSIX** [comment]
This'll be implemented in METAL Composer if there's enough want for it

**Comment by GlitchyPSIX** [comment]
Done, to be added in Alpha 2 release (not compatible with current M64MM3 build)
