### ISSUE TITLE
Angle modifier for animations [Suggestion]

### ISSUE THREAD

**Issue by xen0va** [projectcomet64/M64MM#15]
There could be a feature in M64MM where you could determine the angle Mario's model is set to. This could allow for a better video effects and do other things that normally aren't allowed due to camera and other limitations. A small mock-up of what it would look like in game is included below
![{E15520FD-9D05-4BEC-B964-DBFB3EA13813}](https://user-images.githubusercontent.com/59028040/71330356-66ee9080-250b-11ea-82eb-b914b04c5953.png)

**Comment by GlitchyPSIX** [comment]
Will be a bit hard, but sounds possible

**Comment by GlitchyPSIX** [comment]
Delayed until another project is done.
