### ISSUE TITLE
Option to disable freezing keybinds [Suggestion]

### ISSUE THREAD

**Issue by Llennpie** [projectcomet64/M64MM#16]
Sometimes, while inserting clips into Vegas Pro, I accidentally trigger a keybind which unfreezes or freezes the camera. While keybinds are nice, they can sometimes be annoying. It would be convenient to have the option to disable/enable these.

![image](https://user-images.githubusercontent.com/44985633/71421605-f306d200-2649-11ea-92ac-d857c59e8faa.png)

**Comment by GlitchyPSIX** [comment]
Thanks for the suggestion. M64MM development has been set to continue after the holidays so keep an eye for future releases to see this enhancement included 👍

**Comment by GlitchyPSIX** [comment]
Update: This will be included alongside something that allows you to store application settings for addons and the program's base features. Keep an eye around, I'll be working on it soon
