### ISSUE TITLE
It always crashes

### ISSUE THREAD

**Issue by ggucvgf** [projectcomet64/M64MM#2]
Well, I was trying to do a video for my channel and I needed Mario 64 movie maker. When I opened project 64 and Mario 64 movie maker they founnd the adress,but when I try to swap an animation,remove the HUD or freeze the camera, it crashes and it doesn't affect the game,I mean that I can't do any game changes and when I try to it crashes.
Can someone help me?
I tried to show a record of the bug but I don't know how to do it.

**Comment by GlitchyPSIX** [comment]
You can use [ShareX](http://getsharex.com) or Snipping Tool to get a screenshot of the error shown, if there's any.
It's also useful to know which OS you're using at the time.

**Comment by ggucvgf** [comment]
Well the error I have need to be shown in a video,but I can say that I use windows 7.

**Comment by GlitchyPSIX** [comment]
You can record GIF with ShareX.
Which version of M64MM are you using?

**Comment by ggucvgf** [comment]
2.1

**Comment by GlitchyPSIX** [comment]
Alright, please record your error using ShareX or any other recording tool, and send the video/GIF over here.

**Comment by ggucvgf** [comment]
well it don't support video files

**Comment by GlitchyPSIX** [comment]
Upload to a service like Youtube if it's a video file, or Imgur if it's a GIF.

**Comment by ggucvgf** [comment]
I'm uploading it to a new account I just created for that

**Comment by ggucvgf** [comment]
https://www.youtube.com/watch?v=_e_3r-lM7yA

**Comment by GlitchyPSIX** [comment]
Which antivirus do you use?

**Comment by ggucvgf** [comment]
security agent

**Comment by GlitchyPSIX** [comment]
Try disabling your AV (temporarily) before using M64MM

**Comment by ggucvgf** [comment]
ok

**Comment by ggucvgf** [comment]
doesn't work,well I must leave,see you tomorrow maybe

**Comment by GlitchyPSIX** [comment]
Have you managed to fix your issue? You haven't commented back in a while.

**Comment by GlitchyPSIX** [comment]
It's been a while and you haven't replied. I'll close this for now. Reopen if it happens again.
