### ISSUE TITLE
Refusing to open

### ISSUE THREAD

**Issue by happymichael2009** [projectcomet64/M64MM#20]
I tried opening it, but it wouldn't work. Is there a file I need to run to open it? I'm running Windows 10.

**Comment by xen0va** [comment]
Try right clicking the .dll files and go to properties, then check at the bottom of the general tab if there is a unblock file option. Do that for all .dll files and the .exe file.
Also temporarily disable antivirus software if you have it installed.

**Comment by happymichael2009** [comment]
It still isn't running.

**Comment by xen0va** [comment]
My only other suggestion is to check if the latest version of .NET framework is installed.
Also, would you happen to have Discord? If so, you can get assistant on the Project Comet Discord server.
The invite can be found in the link below.
https://comet.glitchypsi.xyz

**Comment by happymichael2009** [comment]
I do have discord, and .NET framework is installed.

**Comment by GlitchyPSIX** [comment]
This issue is related to permissions granted on loaded assemblies (Will affect any addon that is loaded)
I will make a hotfix for this and future versions will have the same fix if I find a proper one.

**Comment by happymichael2009** [comment]
(Forgot to close this) The fix was removing the extension, so I hope it gets fixed so I can use the extension without it not working

**Comment by GlitchyPSIX** [comment]
(removing the extension from an addon will just make M64MM not read it, and as the only prebundled addon is MComposer then it'll work if you have nothing else.
this is still a bug, so please keep it open until I actually make the fix.)

**Comment by happymichael2009** [comment]
oh ok

**Comment by GlitchyPSIX** [comment]
After trying for very long I am unable to reproduce this issue. If anybody else can reproduce this problem, please, let me know and ask me to reopen this issue.
