### ISSUE TITLE
Feature Request: Base address lost failsafe

### ISSUE THREAD

**Issue by xen0va** [projectcomet64/M64MM#22]
It would be useful if functions like freeze camera reset to default if the base address was lost or if Project64 wasn't open. This would prevent the issue where the camera gets stuck at the start of the game if you forget freeze camera on.

**Comment by GlitchyPSIX** [comment]
Funny enough this was introduced in 2.1
Sure, will be fixed

**Comment by GlitchyPSIX** [comment]
Fixed (And you have *NO* idea the avalanche you just unleashed by requesting this...)
