### ISSUE TITLE
New Camera Angle plz

### ISSUE THREAD

**Issue by MrKromiumMCYT** [projectcomet64/M64MM#24]
If there a new camera angle in Mario 64 Movie Maker this we’ll be good

What if there a keyflames or something like that

If you record a charcher that we’ll be good

**Comment by GlitchyPSIX** [comment]
I will assume some of the wording in this message as I cannot completely understand it.

I'll look into it.

**Comment by GlitchyPSIX** [comment]
I can't really figure out exactly what you want, so I will close this. Please find a way to explain what you wish and reopen this issue.
