### ISSUE TITLE
Control Ennemies and possibility to change hands!

### ISSUE THREAD

**Issue by Burgy158** [projectcomet64/M64MM#25]
If we can change the hand and can use it for every animations (peace, flat in water or flying) And possibility to control every ennemies with their own animations and have a free camera to move whanever we want.

Can be great!

**Comment by GlitchyPSIX** [comment]
This is very interesting and possibly hard, so I will slate it for after M64MM3 Alpha 2.

**Comment by GlitchyPSIX** [comment]
Decided to think of it as an addon. It's a bit off-bounds to have it in the base program just yet, at least.
