### ISSUE TITLE
freeze camera issue

### ISSUE THREAD

**Issue by ItzRevandra** [projectcomet64/M64MM#26]
i play mario 64 greenscreen when i freeze camera its look like this
![image](https://user-images.githubusercontent.com/70645676/93160918-9600fe00-f73b-11ea-901b-8cbfc0a1fa58.png)

**Comment by GlitchyPSIX** [comment]
This is a common issue. It has a workaround, see here for instructions:
[https://comet.glitchypsi.xyz/m64mm/intermediate_tips/zoomout.html](https://comet.glitchypsi.xyz/m64mm/intermediate_tips/zoomout.html)

**Comment by GlitchyPSIX** [comment]
Closing this issue as there is a feature coming that will help with this quirk from SM64.
