### ISSUE TITLE
How can I use the alpha2

### ISSUE THREAD

**Issue by SJG4** [projectcomet64/M64MM#27]
yeahhhh, I got no idea on how to use it

**Comment by GlitchyPSIX** [comment]
Please be more specific. What issue are you facing?

**Comment by SJG4** [comment]
![image](https://user-images.githubusercontent.com/73476067/97806879-dce37e00-1c2b-11eb-9e05-ab57e0d68e03.png)
so like, what do I do here? I already downloaded it, just trying to figure out what to do with it

**Comment by GlitchyPSIX** [comment]
You're looking at the source. Check [this page](https://github.com/projectcomet64/M64MM/releases/tag/v3.0-alpha2) to download the program.
