### ISSUE TITLE
Code cleanup and optimization

### ISSUE THREAD

**Issue by GlitchyPSIX** [projectcomet64/M64MM#3]
* Currently, M64MM's program logic is very tied to the UI.
* The code needs to be cleaned.

- [x] Remove unnecessary writing/reading methods
- [x] Change the SwapEndian method so it returns an array instead of changing the original array (The current behavior is actually unintended.) [**Halfway done**]
- [x] Separate ALL logic code from UI (As much as I could for now.)

**Comment by prettytofugirl** [comment]
a lot of the code is still tied with the GUI, why is this closed?

**Comment by GlitchyPSIX** [comment]
To be reopened at a later date, I'm shifting priorities right now and I realized that as I go with these the GUI code will decouple itself
