### ISSUE TITLE
Project64 Is Not Open Error

### ISSUE THREAD

**Issue by thebugga** [projectcomet64/M64MM#31]
Hello im having an error wich it says that project64 is not open even though that Project64 is open. that means i cant freeze the screen or use color codes. can someone pls help me? 
![Captura de Tela (67)](https://user-images.githubusercontent.com/55263057/128557442-67b3fc5d-f197-442a-bfc3-4c8b5d8b15a3.png)

**Comment by GlitchyPSIX** [comment]
Hmmm, is Project64 by any chance started as administrator? M64MM will not be able to detect it if it is.

**Comment by thebugga** [comment]
> Hmmm, is Project64 by any chance started as administrator? M64MM will not be able to detect it if it is.

i did not work

**Comment by GlitchyPSIX** [comment]
No, no, I mean that you cannot have any open as administrator, this may bring issues

But in the case none are, check in Tools and click Scan for Project64

**Comment by ssdip** [comment]
> No, no, I mean that you cannot have any open as administrator, this may bring issues
> 
> But in the case none are, check in Tools and click Scan for Project64

I simply dosent work but in more detail it happens while opening for the second or third time or by opening sm64 rom manager or any sm64 editing software i think its because pc of my cheap pc.

**Comment by GlitchyPSIX** [comment]
One moment, reposting because I have somehow edited one of your responses 😐


Mind coming over to the Discord so you can screen share the problem? You can find the invite in the top bar in https://comet.glitchypsi.xyz

**Comment by GlitchyPSIX** [comment]
You've not asked for further help neither here nor in the Discord. Is this still happening?
I'll close the issue soon if I get no answer.

**Comment by thebugga** [comment]
> You've not asked for further help neither here nor in the Discord. Is this still happening?
> I'll close the issue soon if I get no answer.

i wont join the server im under 13 u might know me by the name flaming hot toons and yes its still broken

**Comment by Llennpie** [comment]
In Task Manager under the *Details* tab, check if there is a process with the name `Project64.exe`.
Here's an example (I'm using Project64 1.6 so the icon may look different):

![image](https://user-images.githubusercontent.com/44985633/131321206-28afba7a-d386-40ad-8762-4e107793ee79.png)

If the `Project64.exe` file was renamed, or the process name is different, it's possible M64MM won't be able to detect it.

![image](https://user-images.githubusercontent.com/44985633/131321939-ad6f833c-e259-4f97-a3a9-77119835931a.png)

**Comment by GlitchyPSIX** [comment]
Closing this issue for cleanup. If this is still an issue, please reopen and explain if the tips given don't help.
