### ISSUE TITLE
when i put diffrent colors on mario just srables off the colors but theres marios normal colors on it but the colors i puted but all messy on the model can u fix this i l send u a pic

### ISSUE THREAD

**Issue by fuckurmomisgayAnimation** [projectcomet64/M64MM#32]

**Comment by GlitchyPSIX** [comment]
I will ASSUME you mean the recent issue with lighting in GLideN64

I may fix this in the future at my own discretion, but either 1. use an older version of GLideN64 (4.0 recommended), or follow [this video](https://www.youtube.com/watch?v=38Gi6KvbVcE) to enable per-pixel lighting, which gets rid of this.
