### ISSUE TITLE
color code issues (new to m64mm)

### ISSUE THREAD

**Issue by domlol10** [projectcomet64/M64MM#34]
so recently ive been wanting to do smg4 like videos and ive discovered m64mm (i use version 6) and for some reason when i try to do color codes like smg4 (default color code) it mixes mario and smg4's colors in a weird way, like her
![Screenshot (989)](https://user-images.githubusercontent.com/91208444/134372558-1dc4b50b-588e-4fa2-9498-b389f3bc62d5.png)
e

is there a way to fix it or am i using an unrecommended version??

**Comment by GlitchyPSIX** [comment]
This is common if you use Project64 3.0's GlideN build. Please, check [this answer](https://github.com/projectcomet64/M64MM/issues/33#issuecomment-911048901) for a solution to your problem outside of M64MM.

**Comment by GlitchyPSIX** [comment]
Closing now, assuming you have fixed your issue. If any other problem arises, let me know.
