### ISSUE TITLE
green screen packs not working (for mario machinima)

### ISSUE THREAD

**Issue by AudricXDlmao** [projectcomet64/M64MM#35]
(i'm sorry i know this isn't related to the movie maker but i really need help)

When i got a SM64 Mario and Luigi Eyes pack made by Weegiepie, I opened it as a ROM, and it didn't work properly. When i pressed start, it froze at a white screen and didn't do anything, please help me, i am new to mario machinima and i need help please. (and also when i loaded a chroma save state, it said that it is not identical and it then crashes.)

**Comment by GlitchyPSIX** [comment]
I don't think I can help much with that here. This appears to be a problem with your emulator and not M64MM itself.

**Comment by AudricXDlmao** [comment]
ok sorry. I thought you could be the person that could help.

**Comment by GlitchyPSIX** [comment]
I can recommend instead to join the Project Comet Discord since there more topics can be discussed that aren't just M64MM

https://comet.glitchypsi.xyz
