### ISSUE TITLE
this bug is driving me Nuts.

### ISSUE THREAD

**Issue by Mydadisacomputer** [projectcomet64/M64MM#37]
When i start up SM64MM its normal. But when i open Project 64 i get a error heres the error message
"Unhandled expection has occurred in your application if you click Continue the application will ignore this error and attempt to continue if you click Quit. the application will close immediatley Arithmetic operation resulted in an overflow" here's the code "See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OverflowException: Arithmetic operation resulted in an overflow.
   at M64MM.Utils.Core.ReadBytes(Int64 address, Int64 size)
   at M64MM.Utils.Core.FindBaseAddress()
   at M64MM2.MainForm.Update(Object sender, EventArgs e)
   at M64MM2.MainForm.<.ctor>b__7_2(Object a, EventArgs b)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
M64MM
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0.0
    CodeBase: file:///C:/Users/Ali/Desktop/3.0.0-alpha6/M64MM.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
M64MM.Utils
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Ali/Desktop/3.0.0-alpha6/M64MM.Utils.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
M64MM.Addon
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Users/Ali/Desktop/3.0.0-alpha6/M64MM.Addon.DLL
----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/Users/Ali/Desktop/3.0.0-alpha6/Newtonsoft.Json.DLL
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4110.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.3761.0 built by: NET48REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box." Ignore the code if you want. Now. When i press Continue It keeps repeating the same message over and over again. Any help? Please make a build where you fix this bug Thanks

**Comment by GlitchyPSIX** [comment]
This looks like an addon issue!
Please try the following and report back to me:
1. Remove all Addons (put them in a different folder)
2. Put each addon one by one back in the Addons folder
3. Check which one makes M64MM crash like this

When you find out which does, please reply.

**Comment by Mydadisacomputer** [comment]
i have no addons
another way plz?

**Comment by GlitchyPSIX** [comment]
Right. What version of M64MM and Project64 are you using?

**Comment by Mydadisacomputer** [comment]
3.0.0 M64MM and 3.0.1 project 64

**Comment by GlitchyPSIX** [comment]
Which M64MM3 alpha?

**Comment by Mydadisacomputer** [comment]
6TH!

**Comment by GlitchyPSIX** [comment]
OK. I will need some more info:
- Which OS you're using (use `winver` in Search or Run to find out)
- Is your OS 64 or 32 bit? (find out in System Properties)
- Whether this happens starting either PJ64 or M64MM in Administrator
- Whether this happens with every ROM you use
- Whether this happens with a different version of Project64
- whether this happens when the game is running, or before it is.

**Comment by Mydadisacomputer** [comment]
1 Windows
2 32 bit
3 Administrator ain't count ITS THE SAME
4 same version i said of project64
5 before running and startup makes M64MM error

**Comment by Mydadisacomputer** [comment]
windows 10 btw

**Comment by Mydadisacomputer** [comment]
happens with every Rom. Golden eye Mario kart 64 ALL can you make a build for this fix i've been waiting for about 1 week for an update

**Comment by GlitchyPSIX** [comment]
I will investigate this bug. It may take a while.

Additionally, please consider moving to a 64-bit OS, if your processor supports it.

**Comment by Mydadisacomputer** [comment]
fuck 64 bit

**Comment by GlitchyPSIX** [comment]
I will actually drop support for 32-bit OSs in 2025 (when Windows 10 is no longer supported), so consider upgrading sometime and be less rude.

**Comment by Mydadisacomputer** [comment]
Hmmm info do i need another mother board for that or info on how to upgrade without any errors?

**Comment by GlitchyPSIX** [comment]
This is the kind of topic that depends in your setup, so I recommend doing your own research. Here's some pointers:

[32-bit and 64-bit Windows: Frequently asked questions (Microsoft Support)](https://support.microsoft.com/en-us/windows/32-bit-and-64-bit-windows-frequently-asked-questions-c6ca9541-8dce-4d48-0415-94a3faa2e13d)

[How do I check whether my hardware is 64-bit capable in Windows? (Superuser)](https://superuser.com/a/251052)

**Comment by Mydadisacomputer** [comment]
okay thanks gudbye My dad is a- a compudah

**Comment by GlitchyPSIX** [comment]
After some research, I have come to the conclusion that it is **unfeasible** to fix this particular issue from within M64MM. If I were to fix this, I would need to **_break current addon compatibility_** for 64 bit as well, or make a separate 32 bit version, and also make 32 bit versions of all existing addons. This is extremely cumbersome, especially because there are a handful of easier ways, as I will outline below:

* First and foremost, if possible, upgrade to a 64-bit system. Your system will likely be unsupported in the coming years, and you'll want to use M64MM and other software after 32-bit systems are no longer supported at all.

Now, if you cannot upgrade to a 64-bit system, here's a few options you have:

1. Use Project64 **1.6 or 1.7 or 2.0**. Do not use >2.0, 3.x or 4.x

2. Use any Project64 beyond 2.0, but adding `Fixed Rdram Address=536870912` to the `Project64.cfg` file as you can see below:
![image](https://user-images.githubusercontent.com/11571952/143905411-01ea9d91-8b5c-4d49-9ffe-3c310103a71e.png)
![image](https://user-images.githubusercontent.com/11571952/143905895-6f95f89e-cbe6-427f-b893-027864665b19.png)
![image](https://user-images.githubusercontent.com/11571952/143906097-6a8daaf7-c44c-4382-948c-5ee131b0ed99.png)
This will make PJ64 use a fixed RAM address with more than enough space for M64MM to run correctly.

_It's important to note that even M64MM2 will be affected by this._
