### ISSUE TITLE
Opening M64MM While running Project64 doesn't work

### ISSUE THREAD

**Issue by MasterNama17083** [projectcomet64/M64MM#38]
Hello. I know what's happening M64MM Program
![image](https://user-images.githubusercontent.com/80534869/143874684-0e8751cd-935a-4084-883b-614ce5003e0f.png)

**Comment by MasterNama17083** [comment]
![image](https://user-images.githubusercontent.com/80534869/143875893-9fc82808-43f0-4cb6-a095-12fb7f50d05e.png)
I'm using 1.6, I clicked for `Tools >> Scan For PJ64` and results will not work.

**Comment by GlitchyPSIX** [comment]
Question, are you starting any PJ64 as Administrator?

**Comment by MasterNama17083** [comment]
> Question, are you starting any PJ64 as Administrator?

Yeah. It still running administrator user

**Comment by MasterNama17083** [comment]
I see still running message says `"Project64 is not open"`. I clicked `Frozen: ON` results will works for me.

**Comment by MasterNama17083** [comment]
![20211201_124335](https://user-images.githubusercontent.com/80534869/144188604-448eb2fc-29c0-413e-866d-efde4239102f.png)
2 days ago

**Comment by GlitchyPSIX** [comment]
I see. How odd.

Please do not start PJ64 as administrator, because this will stop M64MM from being able to access it.

Since you seem to have fixed this issue, I will close this issue. If you do encounter it again, please re-open this issue with the steps you took to find the problem again.
