### ISSUE TITLE
Installing on windows?

### ISSUE THREAD

**Issue by PaperVb64** [projectcomet64/M64MM#39]
i don't know how to mod sm64 on project64 please help me

**Comment by GlitchyPSIX** [comment]
You don't really have to "install" M64MM. Just extract and run **`M64MM.exe`**.

Make sure you're downloading the 7Z from the **[Releases tab,](github.com/projectcomet64/M64MM/releases/latest)** and that you're **not downloading the source code**. You cannot execute the source code like a program.

**Comment by PaperVb64** [comment]
Ok thx.
________________________________
