### ISSUE TITLE
Mario 64 Movie Maker isn't detecting Project 64 1.7

### ISSUE THREAD

**Issue by Haxon-Repo** [projectcomet64/M64MM#43]
One day I started up my pc to make a blooper and then it says project 64 is not open. Is this something with me only? Or...?

**Comment by GlitchyPSIX** [comment]
I need to know some information.

1. M64MM version
2. Exact PJ64 version
3. Operating system
4. Operating system architecture (Is it 32 bit or 64 bit?)
5. SM64 ROM Name (filename), or Region

**Comment by Haxon-Repo** [comment]
Ok its M64MM3 alpha 6
it is project 64 1.7.0.5.0
it is windows 10 64-bit
and its a us sm64 rom that i got from wow-roms

**Comment by GlitchyPSIX** [comment]
Alright, are you starting either M64MM or PJ64 as administrator?

**Comment by Haxon-Repo** [comment]
I start the Project 64 as admin because if I dont, things get messed up in-game after like 10 minutes. I tried it with Project 64 2.0.0.14, but it still has the same result even if I press scan for Project 64 in M64MM

**Comment by GlitchyPSIX** [comment]
Starting Project64 as administrator makes M64MM unable to interface with it. I do not recommend doing that.

What do you mean things get messed up in-game after 10 minutes? That's not normal behavior, and it would also happen even if you start PJ64 as admin; it doesn't have to do with that.

**Comment by Haxon-Repo** [comment]
Well after 10 or so minutes, the games textures all disappear and there is no color within the game except for Mario's eyes at times

**Comment by GlitchyPSIX** [comment]
This may be a problem with one of your video plugins or cheats. I advise checking what's up. 

Do not start PJ64 as administrator in order for M64MM to work again.

**Comment by Haxon-Repo** [comment]
Oh ok, because it just started working! Thank you, Glitchy!
