### ISSUE TITLE
Ability to modify the copied diffuse and ambient RGB colors

### ISSUE THREAD

**Issue by prettytofugirl** [projectcomet64/M64MM#44]
(For reference, diffuse is the lighter shade of each color grouping and ambient is the darker shade of each color grouping .)

M64MMs built-in Color Code Editor and the optional SPARK Color Code Editor currently do not let you modify the copied diffuse and ambient RGB colors of each color grouping in any shape or form, neither does it take notice of them, causing a "marble effect" as the colors clash with the originals. This bug has been reported already (#32, #33, #34), however they're mislabeled as being emulation issues, even though it happens on console (as proven by the video linked below)

Upon further inspection of the `gbi.h` header included in libultra, we can see that these copies are located right after the original values. Thus, they're very easily modifiable, as you only need to move 4 bytes forward from the original colors.
```c
/*
 * Light structure.
 *
 * Note: only directional (infinite) lights are currently supported.
 *
 * Note: the weird order is for the DMEM alignment benefit of 
 * the microcode.
 *
 */

typedef struct {
  unsigned char col[3];         /* diffuse light value (rgba) */
  char          pad1;
  unsigned char colc[3];        /* copy of diffuse light value (rgba) */
  char          pad2;
  signed char   dir[3];         /* direction of light (normalized) */
  char          pad3;
} Light_t;

typedef struct {
  unsigned char col[3];		/* ambient light value (rgba) */
  char          pad1;
  unsigned char colc[3];	/* copy of ambient light value (rgba) */
  char          pad2;
} Ambient_t;

/* [...] */

/* NOTE(bjrkk): This is the structure used for the color groups present in Marios model. */
typedef struct {
    Ambient     a;
    Light       l[1];
} Lights1;
```

What I personally find strange is that this effect has already been documented back in 2009 by yoshielectron, the creator of the original SM64 Color Code Generator that was considered standard at the time, as seen here: https://youtu.be/N-LG3DF8vHM
As a fix, yoshielectron included the ability to modify the copied diffuse RGB colors for each color grouping in the next iteration of his tool.

For artistic purposes, I believe the copies should be modifiable, as they allow for certain effects to be achieved (e.g. a glow effect by setting the copy diffuse RGB values to white)

![example](https://user-images.githubusercontent.com/61477479/165757970-53201570-44ea-4429-8971-37b005d053a6.png)
Here's an example of it being used for the sake of achieving a glow effect on the gloves and shoes.

While it is true that older, more common video plugins don't emulate this properly, this will become more of a problem as N64 emulation becomes more and more accurate overtime; and as seen previously, it is becoming an issue. Telling people to use an older version of GlideN64, or to enable per-pixel lighting/Phong shading in their GlideN64 settings is, in my opinion, a very inadequate solution; especially when Gouraud shading might be artistically preferred.

glitchypsi pls fix

**Comment by GlitchyPSIX** [comment]
The fix for this is already considered for the merge between SPARK Studio and Appearance Settings. It has been widely ignored before despite documentation due to the fact no video plugin reliably caused any issues with the omission of said values.

**Comment by prettytofugirl** [comment]
@GlitchyPSIX When is the merge happening? And again, despite widely being "ignored", I still believe it'll become an issue overtime as N64 emulation becomes more accurate and standards change, but I digress.

**Comment by GlitchyPSIX** [comment]
> @GlitchyPSIX When is the merge happening?

Beta 1.

> And again, despite widely being "ignored", I still believe it'll become an issue overtime as N64 emulation becomes more accurate and standards change, but I digress.

Important to notice in my wording that I acknowledge this and have already taken the necessary logical steps to fix it in a near future.

**Comment by prettytofugirl** [comment]
My bad, I misread. Alright, thank you.
