### ISSUE TITLE
It says pj64 isnt open when it is

### ISSUE THREAD

**Issue by ShadicDaim** [projectcomet64/M64MM#48]
It says  that they cant find pj64,i am new to this whole thing and i am 

Pj64 isnt open.

I'm on Windows 10
]

**M64MM environment**
 - Version: [the newest one,not beta]
 - Installed addons: non

**Comment by GlitchyPSIX** [comment]
# Please rewrite your bug report, and fill the entire template. I do not understand this.
SM64 must be running in Project64 when you use M64MM.
