### ISSUE TITLE
It says pj64 isnt open when it is.

### ISSUE THREAD

**Issue by ShadicDaim** [projectcomet64/M64MM#49]
**Describe the bug**
I open pj 64 then M64MM and it says  it is not open.

**To Reproduce**
1. Go to 'project 64'
2. Open sm64 green screen
3. Click on 'M64MM.'

**Expected behavior**
Project 64 isnt open (when it is).

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ Windows 10]
 - Version: [latest]
 - Architecture: [64 bit]

**Emulator environment (please complete the following information):**
 - Emulator: [e.g. Project64]
 - Version: [latest]
 - Installed emulator plugins - non

**M64MM environment**
 - Version: [2.1.1]
 - Installed addons: non

**Additional context**
Non.

**Comment by GlitchyPSIX** [comment]
Try using **M64MM3** Beta 1 first. Beta 1 can tell you if you're using Project64 as administrator, which might be the problem you are facing.

M64MM2 is no longer supported.
