### ISSUE TITLE
M64MM3 cant open.

### ISSUE THREAD

**Issue by ShadicDaim** [projectcomet64/M64MM#50]
**Describe the bug**
Cant open file.

**To Reproduce**
Steps to problem:
1.Download m64mm3'
.'
2. See error

**Expected behavior**
cant open it

**Screenshots**
.
![Screenshot (15)](https://user-images.githubusercontent.com/106035043/169715499-5d563caf-9280-40fc-b795-48b153c34aaf.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [latest]
 - Architecture: [ 64 bit]

**Emulator environment (please complete the following information):**
 - Emulator: [e.g. Project64]
 - Version: [latest]
 - Installed emulator plugins non

**M64MM environment**
 - Version: [latest]
 - Installed addons: non

**Additional context**

**Comment by GlitchyPSIX** [comment]
![image](https://user-images.githubusercontent.com/11571952/169715701-af449acf-a847-4222-acd1-447b59492118.png)
Open the 7z file using 7Zip.
Download 7Zip here: https://7-zip.org
