### ISSUE TITLE
Addons refuse to load in M64MM Beta 1

### ISSUE THREAD

**Issue by MasterNama17083** [projectcomet64/M64MM#52]
**Describe the bug**
I'm using V-Alpha03 and the latest version to see all addons it doesn't load it.

**To Reproduce**
1. Go to 'M64MM Alpha03'
2. Click on 'Addons'

**Expected behavior**
I know what three of the addon's files are broken or require the latest version.

**Screenshots**
![image](https://user-images.githubusercontent.com/80534869/181571869-e65bd8f6-aff5-4fbe-bbb3-8f187f8e16f7.png)
![image](https://user-images.githubusercontent.com/80534869/181573454-0559d9d1-ab76-4291-a650-9ea33b2ac036.png)
#
**3.0.0.0-beta:**
![image](https://user-images.githubusercontent.com/80534869/181574649-e9c8f49c-086b-48aa-9266-a48b98451fd2.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 19041.450
 - Architecture: 64-bit

**Emulator environment (please complete the following information):**
 - Emulator: Project64
 - Version: 4.0.0.5811-dev
 - Installed emulator plugins (with their versions): GLideN64 rev. 47b0de1

**M64MM environment**
 - Version: V-Alpha03 or the latest something
 - Installed addons: METAL Composer, SPARK Studio & METAL Twister

**Additional context**
None, maybe.

**Comment by GlitchyPSIX** [comment]
You're using an outdated version of M64MM. Install M64MM3 Beta 1 Hotfix 1.

**Comment by MasterNama17083** [comment]
> You're using an outdated version of M64MM. Install M64MM3 Beta 1 Hotfix 1.

it doesn't work but it says "Addon Warnings".
@GlitchyPSIX  **EDIT:** I copied `METAL Composer (MetalComposer.dll)` file to `m64mm3-beta1.h1\Addons` and opening up the m64mm application will not load one addon.

**Comment by GlitchyPSIX** [comment]
Are these addons at their latest versions? There's a chance that old addons will no longer work with newer versions.

**Comment by GlitchyPSIX** [comment]
Does this still happen? I will be closing the issue if this does not happen anymore.
