### ISSUE TITLE
If you open M64MM3 with an older .config file, the file gets emptied and M64MM3 gives an error on the next run

### ISSUE THREAD

**Issue by vazhka-dolya** [projectcomet64/M64MM#53]
Let's suppose we have an older M64MM3 version, like alpha 4 for example.
1. Copy the .config file from the older version of M64MM3 into a newer version's folder
2. Open the newer version, the .config file should be empty now
3. Close and reopen it, it will give an error while trying to read from an empty file

Expected behavior:
M64MM3 opens and adds the new options to the old .config file or something similar to that.

Desktop:
 - OS: Windows 10 Pro
 - Version: 21H2
 - Architecture: 64 bit

M64MM3 environment:
 - The version the .config file was taken from: Alpha 4
 - The version the .config file was copied to: Beta 1
 - Installed addons: METAL Composer, Orchestrator, SPARK Studio, Twister, XStudio Mini

**Comment by GlitchyPSIX** [comment]
Very interesting, I thought I managed to fix this bug before
Though, question, what version of METAL Composer do you have? I made a fix to it that helped with something on the same vein.

**Comment by vazhka-dolya** [comment]
Oh, my bad, I had an outdated METAL Composer, updating it fixed the issue
