### ISSUE TITLE
when i on any animation in m64mm 3 alpha 8.b1 it doesn t work only freezing and color is working.

### ISSUE THREAD

**Issue by hiitsmejs** [projectcomet64/M64MM#59]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. 22]
 - Architecture: [e.g. 64 bit]

**Emulator environment (please complete the following information):**
 - Emulator: [e.g. Project64]
 - Version: [e.g. iOS8.1]
 - Installed emulator plugins (with their versions): [e.g. GlideN 4.0]

**M64MM environment**
 - Version: [e.g. 3.0 Beta 1]
 - Installed addons: (e.g. METAL Composer, SPARK Studio)

**Additional context**

**Comment by GlitchyPSIX** [comment]
# **the template was not filled at all. please fill the template.**

**Comment by hiitsmejs** [comment]
I didn't understand.

**Comment by GlitchyPSIX** [comment]
The template has spaces where you must write information related to your issue. It helps me diagnose the issue much faster. Which part did you not understand?
