### ISSUE TITLE
base address not found

### ISSUE THREAD

**Issue by CreepaTate** [projectcomet64/M64MM#61]
### Make sure you're filling the right template the right way.

- [X] I confirm that this is a bug, perceived as a bug, a mistake or something that needs real fixing as oppossed to an enhancement or feature request.
- [X] I faithfully believe this is for M64MM and not an addon with an existing repository.

### Describe the bug

base address not found when Project64 1.6 is open.

### Reproduction steps

error appeared after using 3 times

### Screenshots

![M64MM Classic 3 0 0 0-alpha8 b1 6_5_2023 4_08_35 PM](https://github.com/projectcomet64/M64MM/assets/135281744/790b4dee-92d4-4e55-a2b9-b4a2ec3107e2)

### Computer Environment

OS:  Windows 11
Version: 22H2

### Emulator Environment

Emulator: Project64
Version: 1.6

### M64MM Environment

Version: 3.0

**Comment by GlitchyPSIX** [comment]
Are you using a NTSC (a U region) ROM?
On top of that, are you using a ROM that was built with the decomp?

**Comment by CreepaTate** [comment]
> Are you using a NTSC (a U region) ROM? On top of that, are you using a ROM that was built with the decomp?

yes I am.

**Comment by GlitchyPSIX** [comment]
Using a ROM that was built with the decomp is not officially supported as every build is unique, while M64MM only works in a regular or hacked NTSC (U) ROM. If you're using a Decomp ROM build, consider using the original ROM.

**Comment by CreepaTate** [comment]
oh, I didn't mean to say yes to the decomp part I didn't see it at first- I was using one modified with quad64.

**Comment by GlitchyPSIX** [comment]
Noted. May I see a screenshot having both M64MM and PJ64 open?
