### ISSUE TITLE
Frozen is always broken

### ISSUE THREAD

**Issue by SSG64** [projectcomet64/M64MM#63]
### Make sure you're filling the right template the right way.

- [X] I confirm that this is a bug, perceived as a bug, a mistake or something that needs real fixing as oppossed to an enhancement or feature request.
- [X] I faithfully believe this is for M64MM and not an addon with an existing repository.

### Describe the bug

Everytime i use the FUCKING Frozen button it's like "no" Like it just zooms into the sky like it has a mind of it's own. Is there a way to fix this? Cause Soft frozen is way to Crappy

### Reproduction steps

IDK WHAT THE FUCK REPRODCTION STEPS ARE I WNAT TO SUBMIT PROBLEM

### Screenshots

![Screenshot 2023-07-17 161614](https://github.com/projectcomet64/M64MM/assets/139659345/61abd67d-d45d-4864-880e-39c38db9bd45)

### Computer Environment

OS: [e.g. Windows 10]
Version: [e.g. 22]
Architecture: [e.g. 64 bit]

### Emulator Environment

Emulator: [e.g. Project64]
Version: [e.g. iOS8.1]
Installed emulator plugins (with their versions): [e.g. GlideN 4.0]

### M64MM Environment

Version: [e.g. 3.0 Beta 1]
Installed addons: (e.g. METAL Composer, SPARK Studio)

### Additional context

[ceat 2.txt](https://github.com/projectcomet64/M64MM/files/12073579/ceat.2.txt)

Additional note: The logo on peach's castle looks like it was r---d off.*

**Comment by vazhka-dolya** [comment]
This can be fixed by either going inside the castle and turning on Powercam, or by using this cheat code:
```
8032F872 0000
8032F874 0000
8032F875 0000
8032F876 0000
8032F877 0000
8032F878 0000
8032F879 0000
8032F87A 0000
8032F87B 0000
8032F87C 0000
8032F87E 0000
8032F87F 0000
8032F880 0000
8032F881 0000
8032F882 0000
```

**Comment by GlitchyPSIX** [comment]
i am going to give you a chance this once exclusively, but next time fill the template properly and respectfully or i will deny your issue report frame 1

# Zoom-out while freezing

this only happens in specific levels and Powercam exists for this reason
### in a future however this will be fully fixed as the mechanism to hard-freeze the camera will be changed

to use Powercam, assuming you are on the latest version of M64MM:
- enter the castle
- click the CHECKBOX above the HARD FREEZE BUTTON and DO NOT UNCHECK *EVER*
![image](https://github.com/projectcomet64/M64MM/assets/11571952/bd1ea12a-f37d-41ce-8c97-be9db47a8222)
- exit the castle or enter any level

and your camera will behave the same everywhere

# Additional note: The logo on peach's castle looks like it was r---d off.

this is an issue with your video plugin. i suggest changing video plugins
